################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../mbed-dev/targets/TARGET_STM/analogin_api.c \
../mbed-dev/targets/TARGET_STM/analogout_api.c \
../mbed-dev/targets/TARGET_STM/can_api.c \
../mbed-dev/targets/TARGET_STM/gpio_api.c \
../mbed-dev/targets/TARGET_STM/gpio_irq_api.c \
../mbed-dev/targets/TARGET_STM/hal_tick_overrides.c \
../mbed-dev/targets/TARGET_STM/i2c_api.c \
../mbed-dev/targets/TARGET_STM/lp_ticker.c \
../mbed-dev/targets/TARGET_STM/mbed_crc_api.c \
../mbed-dev/targets/TARGET_STM/mbed_overrides.c \
../mbed-dev/targets/TARGET_STM/pinmap.c \
../mbed-dev/targets/TARGET_STM/port_api.c \
../mbed-dev/targets/TARGET_STM/pwmout_api.c \
../mbed-dev/targets/TARGET_STM/rtc_api.c \
../mbed-dev/targets/TARGET_STM/serial_api.c \
../mbed-dev/targets/TARGET_STM/sleep.c \
../mbed-dev/targets/TARGET_STM/stm_spi_api.c \
../mbed-dev/targets/TARGET_STM/trng_api.c \
../mbed-dev/targets/TARGET_STM/us_ticker.c 

OBJS += \
./mbed-dev/targets/TARGET_STM/analogin_api.o \
./mbed-dev/targets/TARGET_STM/analogout_api.o \
./mbed-dev/targets/TARGET_STM/can_api.o \
./mbed-dev/targets/TARGET_STM/gpio_api.o \
./mbed-dev/targets/TARGET_STM/gpio_irq_api.o \
./mbed-dev/targets/TARGET_STM/hal_tick_overrides.o \
./mbed-dev/targets/TARGET_STM/i2c_api.o \
./mbed-dev/targets/TARGET_STM/lp_ticker.o \
./mbed-dev/targets/TARGET_STM/mbed_crc_api.o \
./mbed-dev/targets/TARGET_STM/mbed_overrides.o \
./mbed-dev/targets/TARGET_STM/pinmap.o \
./mbed-dev/targets/TARGET_STM/port_api.o \
./mbed-dev/targets/TARGET_STM/pwmout_api.o \
./mbed-dev/targets/TARGET_STM/rtc_api.o \
./mbed-dev/targets/TARGET_STM/serial_api.o \
./mbed-dev/targets/TARGET_STM/sleep.o \
./mbed-dev/targets/TARGET_STM/stm_spi_api.o \
./mbed-dev/targets/TARGET_STM/trng_api.o \
./mbed-dev/targets/TARGET_STM/us_ticker.o 

C_DEPS += \
./mbed-dev/targets/TARGET_STM/analogin_api.d \
./mbed-dev/targets/TARGET_STM/analogout_api.d \
./mbed-dev/targets/TARGET_STM/can_api.d \
./mbed-dev/targets/TARGET_STM/gpio_api.d \
./mbed-dev/targets/TARGET_STM/gpio_irq_api.d \
./mbed-dev/targets/TARGET_STM/hal_tick_overrides.d \
./mbed-dev/targets/TARGET_STM/i2c_api.d \
./mbed-dev/targets/TARGET_STM/lp_ticker.d \
./mbed-dev/targets/TARGET_STM/mbed_crc_api.d \
./mbed-dev/targets/TARGET_STM/mbed_overrides.d \
./mbed-dev/targets/TARGET_STM/pinmap.d \
./mbed-dev/targets/TARGET_STM/port_api.d \
./mbed-dev/targets/TARGET_STM/pwmout_api.d \
./mbed-dev/targets/TARGET_STM/rtc_api.d \
./mbed-dev/targets/TARGET_STM/serial_api.d \
./mbed-dev/targets/TARGET_STM/sleep.d \
./mbed-dev/targets/TARGET_STM/stm_spi_api.d \
./mbed-dev/targets/TARGET_STM/trng_api.d \
./mbed-dev/targets/TARGET_STM/us_ticker.d 


# Each subdirectory must supply rules for building sources it contributes
mbed-dev/targets/TARGET_STM/analogin_api.o: ../mbed-dev/targets/TARGET_STM/analogin_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/analogin_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/analogout_api.o: ../mbed-dev/targets/TARGET_STM/analogout_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/analogout_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/can_api.o: ../mbed-dev/targets/TARGET_STM/can_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/can_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/gpio_api.o: ../mbed-dev/targets/TARGET_STM/gpio_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/gpio_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/gpio_irq_api.o: ../mbed-dev/targets/TARGET_STM/gpio_irq_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/gpio_irq_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/hal_tick_overrides.o: ../mbed-dev/targets/TARGET_STM/hal_tick_overrides.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/hal_tick_overrides.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/i2c_api.o: ../mbed-dev/targets/TARGET_STM/i2c_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/i2c_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/lp_ticker.o: ../mbed-dev/targets/TARGET_STM/lp_ticker.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/lp_ticker.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/mbed_crc_api.o: ../mbed-dev/targets/TARGET_STM/mbed_crc_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/mbed_crc_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/mbed_overrides.o: ../mbed-dev/targets/TARGET_STM/mbed_overrides.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/mbed_overrides.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/pinmap.o: ../mbed-dev/targets/TARGET_STM/pinmap.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/pinmap.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/port_api.o: ../mbed-dev/targets/TARGET_STM/port_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/port_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/pwmout_api.o: ../mbed-dev/targets/TARGET_STM/pwmout_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/pwmout_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/rtc_api.o: ../mbed-dev/targets/TARGET_STM/rtc_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/rtc_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/serial_api.o: ../mbed-dev/targets/TARGET_STM/serial_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/serial_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/sleep.o: ../mbed-dev/targets/TARGET_STM/sleep.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/sleep.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/stm_spi_api.o: ../mbed-dev/targets/TARGET_STM/stm_spi_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/stm_spi_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/trng_api.o: ../mbed-dev/targets/TARGET_STM/trng_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/trng_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/targets/TARGET_STM/us_ticker.o: ../mbed-dev/targets/TARGET_STM/us_ticker.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/targets/TARGET_STM/us_ticker.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

