################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../mbed-dev/platform/mbed_application.c \
../mbed-dev/platform/mbed_assert.c \
../mbed-dev/platform/mbed_board.c \
../mbed-dev/platform/mbed_critical.c \
../mbed-dev/platform/mbed_error.c \
../mbed-dev/platform/mbed_error_hist.c \
../mbed-dev/platform/mbed_interface.c \
../mbed-dev/platform/mbed_mktime.c \
../mbed-dev/platform/mbed_sdk_boot.c \
../mbed-dev/platform/mbed_semihost_api.c \
../mbed-dev/platform/mbed_stats.c \
../mbed-dev/platform/mbed_wait_api_no_rtos.c 

CPP_SRCS += \
../mbed-dev/platform/ATCmdParser.cpp \
../mbed-dev/platform/CallChain.cpp \
../mbed-dev/platform/FileBase.cpp \
../mbed-dev/platform/FileHandle.cpp \
../mbed-dev/platform/FilePath.cpp \
../mbed-dev/platform/FileSystemHandle.cpp \
../mbed-dev/platform/LocalFileSystem.cpp \
../mbed-dev/platform/Stream.cpp \
../mbed-dev/platform/mbed_alloc_wrappers.cpp \
../mbed-dev/platform/mbed_mem_trace.cpp \
../mbed-dev/platform/mbed_poll.cpp \
../mbed-dev/platform/mbed_retarget.cpp \
../mbed-dev/platform/mbed_rtc_time.cpp \
../mbed-dev/platform/mbed_wait_api_rtos.cpp 

OBJS += \
./mbed-dev/platform/ATCmdParser.o \
./mbed-dev/platform/CallChain.o \
./mbed-dev/platform/FileBase.o \
./mbed-dev/platform/FileHandle.o \
./mbed-dev/platform/FilePath.o \
./mbed-dev/platform/FileSystemHandle.o \
./mbed-dev/platform/LocalFileSystem.o \
./mbed-dev/platform/Stream.o \
./mbed-dev/platform/mbed_alloc_wrappers.o \
./mbed-dev/platform/mbed_application.o \
./mbed-dev/platform/mbed_assert.o \
./mbed-dev/platform/mbed_board.o \
./mbed-dev/platform/mbed_critical.o \
./mbed-dev/platform/mbed_error.o \
./mbed-dev/platform/mbed_error_hist.o \
./mbed-dev/platform/mbed_interface.o \
./mbed-dev/platform/mbed_mem_trace.o \
./mbed-dev/platform/mbed_mktime.o \
./mbed-dev/platform/mbed_poll.o \
./mbed-dev/platform/mbed_retarget.o \
./mbed-dev/platform/mbed_rtc_time.o \
./mbed-dev/platform/mbed_sdk_boot.o \
./mbed-dev/platform/mbed_semihost_api.o \
./mbed-dev/platform/mbed_stats.o \
./mbed-dev/platform/mbed_wait_api_no_rtos.o \
./mbed-dev/platform/mbed_wait_api_rtos.o 

C_DEPS += \
./mbed-dev/platform/mbed_application.d \
./mbed-dev/platform/mbed_assert.d \
./mbed-dev/platform/mbed_board.d \
./mbed-dev/platform/mbed_critical.d \
./mbed-dev/platform/mbed_error.d \
./mbed-dev/platform/mbed_error_hist.d \
./mbed-dev/platform/mbed_interface.d \
./mbed-dev/platform/mbed_mktime.d \
./mbed-dev/platform/mbed_sdk_boot.d \
./mbed-dev/platform/mbed_semihost_api.d \
./mbed-dev/platform/mbed_stats.d \
./mbed-dev/platform/mbed_wait_api_no_rtos.d 

CPP_DEPS += \
./mbed-dev/platform/ATCmdParser.d \
./mbed-dev/platform/CallChain.d \
./mbed-dev/platform/FileBase.d \
./mbed-dev/platform/FileHandle.d \
./mbed-dev/platform/FilePath.d \
./mbed-dev/platform/FileSystemHandle.d \
./mbed-dev/platform/LocalFileSystem.d \
./mbed-dev/platform/Stream.d \
./mbed-dev/platform/mbed_alloc_wrappers.d \
./mbed-dev/platform/mbed_mem_trace.d \
./mbed-dev/platform/mbed_poll.d \
./mbed-dev/platform/mbed_retarget.d \
./mbed-dev/platform/mbed_rtc_time.d \
./mbed-dev/platform/mbed_wait_api_rtos.d 


# Each subdirectory must supply rules for building sources it contributes
mbed-dev/platform/ATCmdParser.o: ../mbed-dev/platform/ATCmdParser.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/ATCmdParser.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/CallChain.o: ../mbed-dev/platform/CallChain.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/CallChain.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/FileBase.o: ../mbed-dev/platform/FileBase.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/FileBase.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/FileHandle.o: ../mbed-dev/platform/FileHandle.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/FileHandle.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/FilePath.o: ../mbed-dev/platform/FilePath.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/FilePath.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/FileSystemHandle.o: ../mbed-dev/platform/FileSystemHandle.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/FileSystemHandle.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/LocalFileSystem.o: ../mbed-dev/platform/LocalFileSystem.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/LocalFileSystem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/Stream.o: ../mbed-dev/platform/Stream.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/Stream.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_alloc_wrappers.o: ../mbed-dev/platform/mbed_alloc_wrappers.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_alloc_wrappers.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_application.o: ../mbed-dev/platform/mbed_application.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_application.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_assert.o: ../mbed-dev/platform/mbed_assert.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_assert.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_board.o: ../mbed-dev/platform/mbed_board.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_board.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_critical.o: ../mbed-dev/platform/mbed_critical.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_critical.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_error.o: ../mbed-dev/platform/mbed_error.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_error.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_error_hist.o: ../mbed-dev/platform/mbed_error_hist.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_error_hist.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_interface.o: ../mbed-dev/platform/mbed_interface.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_interface.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_mem_trace.o: ../mbed-dev/platform/mbed_mem_trace.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_mem_trace.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_mktime.o: ../mbed-dev/platform/mbed_mktime.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_mktime.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_poll.o: ../mbed-dev/platform/mbed_poll.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_poll.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_retarget.o: ../mbed-dev/platform/mbed_retarget.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_retarget.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_rtc_time.o: ../mbed-dev/platform/mbed_rtc_time.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_rtc_time.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_sdk_boot.o: ../mbed-dev/platform/mbed_sdk_boot.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_sdk_boot.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_semihost_api.o: ../mbed-dev/platform/mbed_semihost_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_semihost_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_stats.o: ../mbed-dev/platform/mbed_stats.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_stats.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_wait_api_no_rtos.o: ../mbed-dev/platform/mbed_wait_api_no_rtos.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_wait_api_no_rtos.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
mbed-dev/platform/mbed_wait_api_rtos.o: ../mbed-dev/platform/mbed_wait_api_rtos.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 '-DDEVICE_SERIAL_FC=1' '-DDEVICE_PORTINOUT=1' '-DDEVICE_RTC=1' '-DDEVICE_SERIAL_ASYNCH=1' '-DDEVICE_I2C_ASYNCH=1' '-DDEVICE_SPISLAVE=1' '-DDEVICE_PWMOUT=1' -DTARGET_RTOS_M4_M7 '-DDEVICE_SLEEP=1' -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM '-DDEVICE_SPI_ASYNCH=1' '-DDEVICE_SERIAL=1' -DTARGET_M4 -D__CORTEX_M4 '-D__MBED__=1' '-DDEVICE_FLASH=1' '-DMBED_BUILD_TIMESTAMP=1580513127.6982965' '-DDEVICE_USTICKER=1' '-D__FPU_PRESENT=1' -DTARGET_LIKE_MBED '-DTARGET_NAME=NUCLEO_F401RE' '-DDEVICE_PORTOUT=1' -DTARGET_STM32F401xE '-DDEVICE_INTERRUPTIN=1' -DTARGET_STM32F4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_CORTEX_M -DTOOLCHAIN_GCC -DTARGET_NUCLEO_F401RE -D__MBED_CMSIS_RTOS_CM '-DDEVICE_ANALOGIN=1' -DTARGET_STM32F401RE '-DDEVICE_LPTICKER=1' -D__CMSIS_RTOS '-DTRANSACTION_QUEUE_SIZE_SPI=2' '-DDEVICE_STDIO_MESSAGES=1' -DTARGET_STM '-DDEVICE_SPI=1' -DARM_MATH_CM4 -DUSB_STM_HAL '-DDEVICE_PORTIN=1' -DTARGET_CORTEX -DUSBHOST_OTHER -DTARGET_FF_MORPHO '-DDEVICE_I2CSLAVE=1' -DTARGET_FAMILY_STM32 -DTARGET_RELEASE '-DDEVICE_I2C=1' -DMBED_DEBUG '-DMBED_TRAP_ERRORS_ENABLED=1' -DNDEBUG -DUSE_HAL_DRIVER -DSTM32F401xE -DDEBUG -c -I../usr/src/mbed-sdk -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/drivers" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/hal/storage_abstraction" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/platform" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/targets/TARGET_STM/TARGET_STM32F4/device" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/mbed-dev/cmsis/TARGET_CORTEX_M" -I"C:/STM32/STM32CubeIDE/workspace_1.3.0/F401mbedBase/Core/Inc" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"mbed-dev/platform/mbed_wait_api_rtos.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

